// Curated cross-domain sample from cards.json. Real CDN image URLs.
const CARDS = [
  // ── Fury ────────────────────────────────────────────────
  { id: "blazing-scorcher", name: "Blazing Scorcher", type: "Unit", supertype: null, tags: ["Dragon", "Noxus"],
    cost: "5", energy: 5, might: 5, power: 0, domains: ["Fury"], rarity: "Common", set: "OGN", setLabel: "Origins", num: "1",
    text: "[Accelerate] (You may pay {1}{F} as an additional cost to have me enter ready.)",
    flavor: null,
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/15ed971e4029a92b362a81ccadf309fb81e40b81-744x1039.png?accountingTag=RB",
    price: { nm: 0.48, lp: 0.32, foilNm: 1.85, change: -2.1 } },
  { id: "darius-trifarian", name: "Darius — Trifarian", type: "Unit", supertype: "Champion", tags: ["Trifarian", "Darius", "Noxus"],
    cost: "5{F}", energy: 5, might: 5, power: 1, domains: ["Fury"], rarity: "Rare", set: "OGN", setLabel: "Origins", num: "27",
    text: "When you play your second card in a turn, give me +2 {T} this turn and ready me.",
    flavor: "With overwhelming force.",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/bf7a4900fd2296972c1305a4707c23860bb0522e-744x1039.png?accountingTag=RB",
    price: { nm: 18.50, lp: 14.20, foilNm: 64.00, change: 8.4 },
    altArt: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/df878ecc25160bb7e53b254a609ec243e133e8f1-744x1039.png?accountingTag=RB" },
  { id: "jinx-demolitionist", name: "Jinx — Demolitionist", type: "Unit", supertype: "Champion", tags: ["Jinx", "Zaun"],
    cost: "3{F}", energy: 3, might: 4, power: 1, domains: ["Fury"], rarity: "Rare", set: "OGN", setLabel: "Origins", num: "30",
    text: "[Accelerate] (You may pay {1}{F} as an additional cost to have me enter ready.)\n[Assault 2] (+2 {T} while I'm an attacker.)\nWhen you play me, discard 2.",
    flavor: "I really need a new gun. But don't tell my other guns.",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/d6cac988aa7798945e550eba6841d3993868c4a4-744x1039.png",
    price: { nm: 22.40, lp: 17.80, foilNm: 78.50, change: 12.6 } },
  { id: "draven-showboat", name: "Draven — Showboat", type: "Unit", supertype: "Champion", tags: ["Draven", "Noxus"],
    cost: "5{F}", energy: 5, might: 3, power: 1, domains: ["Fury"], rarity: "Rare", set: "OGN", setLabel: "Origins", num: "28",
    text: "My Might is increased by your points.",
    flavor: "Let's admire me for a bit.",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/7600d6cea66e8146ea2202f72cb9035cb44608a3-744x1039.png",
    price: { nm: 9.20, lp: 7.40, foilNm: 28.10, change: -3.4 } },
  { id: "disintegrate", name: "Disintegrate", type: "Spell", supertype: null, tags: [],
    cost: "4", energy: 4, might: null, power: 0, domains: ["Fury"], rarity: "Common", set: "OGN", setLabel: "Origins", num: "5",
    text: "[Action] (Play on your turn or in showdowns.)\nDeal 3 to a unit at a battlefield. If this kills it, do this: draw 1.",
    flavor: "Ashes, ashes, they all fall down. —Annie",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/a27374ac3a81f3dfefb43c3c3237c23b4883cb5a-744x1039.png",
    price: { nm: 0.35, lp: 0.22, foilNm: 1.10, change: 0 } },
  { id: "cleave", name: "Cleave", type: "Spell", supertype: null, tags: [],
    cost: "1", energy: 1, might: null, power: 0, domains: ["Fury"], rarity: "Common", set: "OGN", setLabel: "Origins", num: "4",
    text: "[Action] (Play on your turn or in showdowns.)\nGive a unit [Assault 3] this turn. (+3 {T} while it's an attacker.)",
    flavor: "Nobody ever won a war without attacking.",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/95d476a1e88ff547fb846149619177bc7e3cea9f-744x1039.png?accountingTag=RB",
    price: { nm: 0.50, lp: 0.35, foilNm: 1.95, change: 2.0 } },
  { id: "magma-wurm", name: "Magma Wurm", type: "Unit", supertype: null, tags: ["Freljord"],
    cost: "8{F}", energy: 8, might: 8, power: 1, domains: ["Fury"], rarity: "Common", set: "OGN", setLabel: "Origins", num: "11",
    text: "Other friendly units enter ready.",
    flavor: "A river of flame in an ocean of ice.",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/f6565b15f65f538804e6a56623c8aa2eedeffc22-744x1039.png",
    price: { nm: 1.80, lp: 1.20, foilNm: 6.40, change: 4.2 } },
  { id: "noxus-hopeful", name: "Noxus Hopeful", type: "Unit", supertype: null, tags: ["Trifarian", "Noxus"],
    cost: "4", energy: 4, might: 4, power: 0, domains: ["Fury"], rarity: "Common", set: "OGN", setLabel: "Origins", num: "12",
    text: "[Legion] — I cost {2} less. (Get the effect if you've played another card this turn.)",
    flavor: "First to the front, first to glory.",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/c3bb6f4cb58feeb50e396d12ec9865c5434025af-744x1039.png",
    price: { nm: 0.42, lp: 0.28, foilNm: 1.40, change: 1.1 } },
  { id: "captain-farron", name: "Captain Farron", type: "Unit", supertype: null, tags: ["Trifarian", "Noxus"],
    cost: "4{F}", energy: 4, might: 5, power: 1, domains: ["Fury"], rarity: "Uncommon", set: "OGN", setLabel: "Origins", num: "15",
    text: "Other friendly units here have [Assault]. (+1 {T} while they're attackers.)",
    flavor: "Forward! Always!",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/4c65e2cae6748590f589ad8b26bc5a20c0d770c2-744x1039.png?accountingTag=RB",
    price: { nm: 2.40, lp: 1.85, foilNm: 8.70, change: -1.2 } },
  { id: "legion-rearguard", name: "Legion Rearguard", type: "Unit", supertype: null, tags: ["Trifarian", "Noxus"],
    cost: "2", energy: 2, might: 2, power: 0, domains: ["Fury"], rarity: "Common", set: "OGN", setLabel: "Origins", num: "10",
    text: "[Accelerate] (You may pay {1}{F} as an additional cost to have me enter ready.)",
    flavor: "The last line of offense.",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/aedece01c7792c689050460db1670e6b9b15b61f-744x1039.png",
    price: { nm: 0.32, lp: 0.20, foilNm: 0.85, change: 0 } },

  // ── Calm ────────────────────────────────────────────────
  { id: "lee-sin-ascetic", name: "Lee Sin — Ascetic", type: "Unit", supertype: "Champion", tags: ["Lee Sin", "Ionia"],
    cost: "4{C}", energy: 4, might: 4, power: 1, domains: ["Calm"], rarity: "Rare", set: "OGN", setLabel: "Origins", num: "100",
    text: "When you play me, buff a friendly unit. (If it doesn't have a buff, it gets a +1 {T} buff.)",
    flavor: "Patience is the sharpest blade.",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/ffe064e002d3b9a366748eb85102a769b2545835-744x1039.png?accountingTag=RB",
    price: { nm: 14.60, lp: 11.20, foilNm: 52.00, change: 5.1 } },
  { id: "yasuo-unforgiven", name: "Yasuo — Unforgiven", type: "Legend", supertype: null, tags: ["Yasuo"],
    cost: null, energy: null, might: null, power: null, domains: ["Calm", "Chaos"], rarity: "Rare", set: "OGN", setLabel: "Origins", num: "259",
    text: "{2}, {E}: Move a friendly unit to or from its base.",
    flavor: "Death is like the wind — always by my side.",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/68e4d3230b785738ae9d86f780f7f5607ef11807-744x1040.png",
    price: { nm: 12.40, lp: 9.80, foilNm: 42.50, change: 18.2 } },
  { id: "leona-radiant", name: "Leona — Radiant Dawn", type: "Legend", supertype: null, tags: ["Leona"],
    cost: null, energy: null, might: null, power: null, domains: ["Calm", "Order"], rarity: "Rare", set: "OGN", setLabel: "Origins", num: "261",
    text: "When you stun one or more enemy units, buff a friendly unit. (If it doesn't have a buff, it gets a +1 {T} buff.)",
    flavor: "The sun gives me strength.",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/822b8bc7987a47498550708b18ef166b121fd620-744x1039.png",
    price: { nm: 9.80, lp: 7.60, foilNm: 32.20, change: 2.4 } },
  { id: "dragons-rage", name: "Dragon's Rage", type: "Spell", supertype: "Signature", tags: ["Lee Sin"],
    cost: "4{B/C}", energy: 4, might: null, power: 1, domains: ["Calm", "Body"], rarity: "Epic", set: "OGN", setLabel: "Origins", num: "258",
    text: "Move an enemy unit. Then do this: Choose another enemy unit at its destination. They deal damage equal to their Mights to each other.",
    flavor: null,
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/7f4cbd4fb340cc13b3fbe0ec0db706464d9b29f4-744x1039.png",
    price: { nm: 6.20, lp: 4.80, foilNm: 22.00, change: -2.0 } },
  { id: "last-breath", name: "Last Breath", type: "Spell", supertype: "Signature", tags: ["Yasuo"],
    cost: "3{C/H}{C/H}", energy: 3, might: null, power: 2, domains: ["Calm", "Chaos"], rarity: "Epic", set: "OGN", setLabel: "Origins", num: "260",
    text: "[Action] (Play on your turn or in showdowns.)\nReady a friendly unit. It deals damage equal to its Might to an enemy unit at a battlefield.",
    flavor: "A whisper before the storm.",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/e7e6dc840210124825f787095541a66ae5cea178-744x1039.png",
    price: { nm: 8.40, lp: 6.50, foilNm: 28.60, change: 6.8 } },

  // ── Mind ────────────────────────────────────────────────
  { id: "heimer-inventor", name: "Heimerdinger — Inventor", type: "Unit", supertype: "Champion", tags: ["Yordle", "Heimerdinger", "Piltover"],
    cost: "3{M}", energy: 3, might: 3, power: 1, domains: ["Mind"], rarity: "Promo", set: "JDG", setLabel: "Judge Promo", num: "111",
    text: "I have all {E} abilities of all friendly legends, units, and gear.",
    flavor: "I do love a good conundrum.",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/5b14a5f9d567c90329c151a8cc72d870b47b1434-744x1039.png",
    price: { nm: null, lp: null, foilNm: 38.40, change: 14.1 } },
  { id: "ahri-alluring", name: "Ahri — Alluring", type: "Unit", supertype: "Champion", tags: ["Ahri", "Ionia"],
    cost: "3{M}", energy: 3, might: 3, power: 1, domains: ["Mind"], rarity: "Rare", set: "OGN", setLabel: "Origins", num: "165",
    text: "When you play me, return target enemy unit to its owner's hand.",
    flavor: "Just one charm and you'll never want to leave.",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/c3bb6f4cb58feeb50e396d12ec9865c5434025af-744x1039.png",
    price: { nm: 11.20, lp: 8.80, foilNm: 38.00, change: 3.2 } },
  { id: "teemo-scout", name: "Teemo — Swift Scout", type: "Legend", supertype: null, tags: ["Teemo"],
    cost: null, energy: null, might: null, power: null, domains: ["Mind", "Chaos"], rarity: "Rare", set: "OGN", setLabel: "Origins", num: "263",
    text: "You may pay {1} to hide a card with [Hidden] instead of {P}.\n{1}, {E}: Put a Teemo unit you own into your hand.",
    flavor: "Captain Teemo on duty.",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/9723181e3392bb61c2aabc804a44f7b0558cedf1-744x1039.png",
    price: { nm: 4.60, lp: 3.50, foilNm: 16.20, change: -1.4 } },

  // ── Body ────────────────────────────────────────────────
  { id: "garen-commander", name: "Garen — Commander", type: "Unit", supertype: "Champion", tags: ["Garen", "Demacia"],
    cost: "4{B}", energy: 4, might: 5, power: 1, domains: ["Body"], rarity: "Rare", set: "SFD", setLabel: "Spiritforged", num: "320",
    text: "When you play me, other friendly units get +1 {T} this turn.",
    flavor: "Demacia! Stand with me!",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/4c65e2cae6748590f589ad8b26bc5a20c0d770c2-744x1039.png?accountingTag=RB",
    price: { nm: 13.40, lp: 10.20, foilNm: 46.00, change: 7.0 } },
  { id: "vex-apathetic", name: "Vex — Apathetic", type: "Unit", supertype: "Champion", tags: ["Vex", "Shadow Isles"],
    cost: "3{B}", energy: 3, might: 3, power: 1, domains: ["Body"], rarity: "Rare", set: "SFD", setLabel: "Spiritforged", num: "412",
    text: "When you play me, return a friendly unit to your hand. Draw 1.",
    flavor: "Ugh. Fine.",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/9566fc064c098bd7f3540f3074dc6353c7ca5663-744x1039.png",
    price: { nm: 6.80, lp: 5.20, foilNm: 22.40, change: 1.6 } },
  { id: "ashe-focused", name: "Ashe — Focused", type: "Unit", supertype: "Champion", tags: ["Ashe", "Freljord"],
    cost: "4{B}", energy: 4, might: 3, power: 1, domains: ["Body"], rarity: "Rare", set: "OGN", setLabel: "Origins", num: "180",
    text: "[Assault 1] When you play me, frost an enemy unit. (Stun it.)",
    flavor: "Steady. Aim. Fire.",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/9cf2d2e59e1bf839cdf5c2a77e95f5d1e871788f-744x1039.png",
    price: { nm: 10.40, lp: 8.20, foilNm: 36.00, change: 4.4 } },

  // ── Chaos ───────────────────────────────────────────────
  { id: "vi-destructive", name: "Vi — Destructive", type: "Unit", supertype: "Champion", tags: ["Vi", "Piltover"],
    cost: "4{H}", energy: 4, might: 4, power: 1, domains: ["Chaos"], rarity: "Rare", set: "OGN", setLabel: "Origins", num: "210",
    text: "When you play me, deal 2 to an enemy unit.",
    flavor: "Punch first. Questions later.",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/68e4d3230b785738ae9d86f780f7f5607ef11807-744x1040.png",
    price: { nm: 8.80, lp: 6.80, foilNm: 28.00, change: -0.8 } },
  { id: "ekko-recurrent", name: "Ekko — Recurrent", type: "Unit", supertype: "Champion", tags: ["Ekko", "Zaun"],
    cost: "3{H}", energy: 3, might: 2, power: 1, domains: ["Chaos"], rarity: "Rare", set: "OGN", setLabel: "Origins", num: "230",
    text: "When I die, return me to your hand at end of turn.",
    flavor: "Took me a while to figure that one out.",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/2906c932c482af17fbb2979a8c42a6992f95d6a6-744x1039.png",
    price: { nm: 14.20, lp: 11.00, foilNm: 48.00, change: 22.1 } },
  { id: "void-seeker", name: "Void Seeker", type: "Spell", supertype: null, tags: [],
    cost: "3{F}", energy: 3, might: null, power: 1, domains: ["Fury"], rarity: "Uncommon", set: "OGN", setLabel: "Origins", num: "24",
    text: "[Action] (Play on your turn or in showdowns.)\nDeal 4 to a unit at a battlefield. Draw 1.",
    flavor: "It's a good day for a hunt. —Kai'Sa",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/5b64b63c6be58ff3c33c7fb3c2dcb168d64e287e-744x1039.png",
    price: { nm: 1.80, lp: 1.40, foilNm: 5.80, change: 2.8 } },

  // ── Order ───────────────────────────────────────────────
  { id: "azir-emperor", name: "Azir — Emperor of the Sands", type: "Unit", supertype: "Champion", tags: ["Azir", "Shurima"],
    cost: "6{O}", energy: 6, might: 5, power: 2, domains: ["Order"], rarity: "Rare", set: "SFD", setLabel: "Spiritforged", num: "501",
    text: "When you play me, summon two 1/0 Sand Soldier tokens.",
    flavor: "Shurima! Your emperor has returned!",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/01faae468720dd5bf5e3fe12ba56c01af70263be-744x1039.png",
    price: { nm: 24.80, lp: 19.40, foilNm: 88.00, change: 12.0 } },
  { id: "lux-illuminated", name: "Lux — Illuminated", type: "Unit", supertype: "Champion", tags: ["Lux", "Demacia"],
    cost: "5{O}", energy: 5, might: 4, power: 1, domains: ["Order"], rarity: "Rare", set: "SFD", setLabel: "Spiritforged", num: "510",
    text: "When you play a spell, deal 1 to all enemy units.",
    flavor: "Light is the answer.",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/d74ba4998df9348408f1400090a0b0737c675fbd-744x1039.png?accountingTag=RB",
    price: { nm: 16.20, lp: 12.80, foilNm: 58.00, change: 6.4 } },
  { id: "annie-fiery", name: "Annie — Fiery", type: "Unit", supertype: "Champion", tags: ["Annie", "Noxus"],
    cost: "2{O}", energy: 2, might: 2, power: 1, domains: ["Order"], rarity: "Rare", set: "SFD", setLabel: "Spiritforged", num: "501",
    text: "When I attack, deal 1 to a unit at a battlefield.",
    flavor: "Tibbers, do the thing.",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/44e805aa0f2928acf1156eef692403df319b333a-744x1039.png?accountingTag=RB",
    price: { nm: 7.20, lp: 5.60, foilNm: 24.20, change: 3.4 } },

  // ── Gear / Spells / Misc ───────────────────────────────
  { id: "iron-ballista", name: "Iron Ballista", type: "Gear", supertype: null, tags: [],
    cost: "3", energy: 3, might: null, power: 0, domains: ["Fury"], rarity: "Uncommon", set: "OGN", setLabel: "Origins", num: "17",
    text: "This enters exhausted.\n{E}: Deal 2 to a unit at a battlefield.",
    flavor: "There's no way they can hit us at this dist-AUGH!",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/9b5cfe757b6067994e17e284eba46433880a1461-744x1039.png",
    price: { nm: 1.20, lp: 0.90, foilNm: 4.40, change: 0.4 } },
  { id: "ravenborn-tome", name: "Ravenborn Tome", type: "Gear", supertype: null, tags: [],
    cost: "3", energy: 3, might: null, power: 0, domains: ["Fury"], rarity: "Rare", set: "OGN", setLabel: "Origins", num: "32",
    text: "{E}: The next spell you play this turn deals 1 Bonus Damage.",
    flavor: "The book is bound in flame-resistant materials, for obvious reasons.",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/81f968126026635e5b9a2fa1048fc979fcd13a1d-744x1039.png",
    price: { nm: 5.40, lp: 4.20, foilNm: 18.80, change: 5.2 } },
  { id: "blind-fury", name: "Blind Fury", type: "Spell", supertype: null, tags: [],
    cost: "4{F}{F}", energy: 4, might: null, power: 2, domains: ["Fury"], rarity: "Rare", set: "OGN", setLabel: "Origins", num: "25",
    text: "[Action] Each opponent reveals the top card of their Main Deck. Choose one and banish it, then play it, ignoring its cost.",
    flavor: null,
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/d74ba4998df9348408f1400090a0b0737c675fbd-744x1039.png?accountingTag=RB",
    price: { nm: 12.20, lp: 9.40, foilNm: 42.00, change: 9.8 } },
  { id: "thermo-beam", name: "Thermo Beam", type: "Spell", supertype: null, tags: [],
    cost: "5{F}{F}", energy: 5, might: null, power: 2, domains: ["Fury"], rarity: "Uncommon", set: "OGN", setLabel: "Origins", num: "22",
    text: "[Action] (Play on your turn or in showdowns.)\nKill all gear.",
    flavor: "Turn the limiter off, the beam is totally stable. —Common Last Words",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/88661e852b864491e6d7f5f087caf4263f61c361-744x1039.png",
    price: { nm: 2.40, lp: 1.80, foilNm: 8.60, change: 1.2 } },
  { id: "scrapyard-champion", name: "Scrapyard Champion", type: "Unit", supertype: null, tags: ["Mech", "Bandle City"],
    cost: "5{F}", energy: 5, might: 5, power: 1, domains: ["Fury"], rarity: "Uncommon", set: "OGN", setLabel: "Origins", num: "20",
    text: "[Legion] — When you play me, discard 2, then draw 2.",
    flavor: "\"Last one standing\" is a bit subjective.",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/10f096d2b469fd73329386e5efe88c9bec667d7c-744x1039.png",
    price: { nm: 3.60, lp: 2.80, foilNm: 13.20, change: 2.1 } },
  { id: "fury-rune", name: "Fury Rune", type: "Rune", supertype: "Basic", tags: [],
    cost: null, energy: null, might: null, power: null, domains: ["Fury"], rarity: "Common", set: "OGN", setLabel: "Origins", num: "7",
    text: "",
    flavor: null,
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/12bcd0cde5d9ff4640e82945001e9fef863530f1-744x1039.png",
    price: { nm: 0.10, lp: 0.05, foilNm: 0.55, change: 0 } },
  { id: "noxus-saboteur", name: "Noxus Saboteur", type: "Unit", supertype: null, tags: ["Trifarian", "Noxus"],
    cost: "3", energy: 3, might: 3, power: 0, domains: ["Fury"], rarity: "Uncommon", set: "OGN", setLabel: "Origins", num: "18",
    text: "Your opponents' [Hidden] cards can't be revealed here.",
    flavor: "Nothing fails like a perfect plan.",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/b78f0c822cb984db24ac3f1956cc8c10f8f88b22-744x1039.png",
    price: { nm: 1.80, lp: 1.40, foilNm: 6.20, change: -0.6 } },
  { id: "brynhir", name: "Brynhir Thundersong", type: "Unit", supertype: null, tags: ["Freljord"],
    cost: "6", energy: 6, might: 5, power: 0, domains: ["Fury"], rarity: "Rare", set: "OGN", setLabel: "Origins", num: "26",
    text: "When you play me, opponents can't play cards this turn.",
    flavor: "Silence. The sky speaks.",
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/44e805aa0f2928acf1156eef692403df319b333a-744x1039.png?accountingTag=RB",
    price: { nm: 11.40, lp: 8.80, foilNm: 38.40, change: 5.6 } },
  { id: "raging-firebrand", name: "Raging Firebrand", type: "Unit", supertype: null, tags: ["Dragon", "Mount Targon"],
    cost: "6{F}", energy: 6, might: 4, power: 1, domains: ["Fury"], rarity: "Rare", set: "OGN", setLabel: "Origins", num: "31",
    text: "When you play me, the next spell you play this turn costs {5} less.",
    flavor: null,
    img: "https://cmsassets.rgpub.io/sanity/images/dsfx7636/game_data_live/9566fc064c098bd7f3540f3074dc6353c7ca5663-744x1039.png",
    price: { nm: 8.60, lp: 6.80, foilNm: 28.40, change: 14.2 } },
];

// Build a price history series (sparkline-style) deterministically per card.
function priceHistory(card, days = 30) {
  if (!card.price?.nm) return [];
  const base = card.price.nm;
  const end = base;
  const start = base / (1 + (card.price.change ?? 0) / 100);
  let h = 0;
  const seed = (card.id || "x").split("").reduce((a, c) => a + c.charCodeAt(0), 0);
  function rand() { h = (h + seed * 9301 + 49297) % 233280; return h / 233280; }
  rand();
  const out = [];
  for (let i = 0; i < days; i++) {
    const t = i / (days - 1);
    const v = start + (end - start) * t + (rand() - 0.5) * base * 0.06;
    out.push({ d: i, v: Math.max(0.01, v) });
  }
  return out;
}

// Public globals
window.CARDS = CARDS;
window.priceHistory = priceHistory;

// Recently viewed / featured decks for the home page
window.FEATURED_DECKS = [
  { id: "fury-legion-aggro", name: "Trifarian — Iron Legion", pilot: "AC", domain: "Fury", price: 168.40, format: "Standard · OGN", winrate: "62%", note: "Aggressive Noxus units backed by Accelerate burst." },
  { id: "lee-sin-tempo", name: "Lee Sin Tempo", pilot: "VR", domain: "Calm/Body", price: 312.80, format: "Standard · OGN", winrate: "58%", note: "Buff-and-redirect. Patient under pressure." },
  { id: "azir-control", name: "Azir Sun-Court", pilot: "KM", domain: "Order", price: 412.20, format: "Standard · SFD", winrate: "55%", note: "Slow-roll Sand Soldier tokens to overwhelming board." },
];
